In [182]:
import pandas as pd

# The raw URL for your specific CSV file
url = 'https://raw.githubusercontent.com/mhmdparichehreh/basketball-scores/main/data/scores.csv'

# Read the CSV
df = pd.read_csv(url)

# Display the first 5 rows
df.head()

,ID,date,gender,team1q1,team2q1,team1q2,team2q2,team1q3,team2q3,team1q4,team2q4,team1tot,team2tot,type
0,1,09/12/2025,M,15,11,12,19,28,20,28,12,83,62,NaN
1,2,09/12/2025,F,20,12,13,17,16,19,10,10,59,58,NaN
2,3,10/12/2025,M,28,22,18,21,14,12,22,27,82,82,NaN
3,4,10/12/2025,F,19,10,18,17,24,26,18,18,79,71,NaN
4,5,10/12/2025,M,10,25,13,22,15,20,17,30,55,97,NaN

In [183]:
df

,ID,date,gender,team1q1,team2q1,team1q2,team2q2,team1q3,team2q3,team1q4,team2q4,team1tot,team2tot,type
0,1,09/12/2025,M,15,11,12,19,28,20,28,12,83,62,NaN
1,2,09/12/2025,F,20,12,13,17,16,19,10,10,59,58,NaN
2,3,10/12/2025,M,28,22,18,21,14,12,22,27,82,82,NaN
3,4,10/12/2025,F,19,10,18,17,24,26,18,18,79,71,NaN
4,5,10/12/2025,M,10,25,13,22,15,20,17,30,55,97,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,186,15/02/2026,F,15,19,14,10,17,13,18,17,64,59,europe
185,187,15/02/2026,M,24,15,30,24,25,24,23,22,102,85,georgia
186,188,15/02/2026,F,29,26,13,27,17,20,15,21,74,94,finland
187,189,15/02/2026,F,15,5,12,10,15,15,9,18,51,48,aj
188,190,15/02/2026,F,17,16,15,20,19,16,23,14,74,66,purtugal

In [186]:
### all the matches: (q1+q2+q3)/3 > q4
hypo1 = (df.iloc[:,3:9].sum(axis=1)/3) > df.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l1 = hypo1.sum()    # sum of true hypothesis
print("1st hypothesis: ", l1, "; Total matches: ", len(hypo1), ", in percent: ", l1/len(hypo1))   # comparison of true hypothesis w/ total matches

1st hypothesis:  89 ; Total matches:  189 , in percent:  0.4708994708994709

In [187]:
### all the matches: (q1+q2+q3)/3 < q4
hypo1 = (df.iloc[:,3:9].sum(axis=1)/3) < df.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l1 = hypo1.sum()    # sum of true hypothesis
print("1st hypothesis: ", l1, "; Total matches: ", len(hypo1), ", in percent: ", l1/len(hypo1))   # comparison of true hypothesis w/ total matches

1st hypothesis:  98 ; Total matches:  189 , in percent:  0.5185185185185185

In [206]:
### women's matches: (q1+q2+q3)/3 > q4
df_female = df[df['gender'] == 'F']     #selecting women's mathches
hypo2 = (df_female.iloc[:,3:9].sum(axis=1)/3)+3 > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l2 = hypo2.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l2, "; Total women's matches: ", len(hypo2), ", in percent: ", l2/len(hypo2))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  51 ; Total women's matches:  68 , in percent:  0.75

In [207]:
### women's matches: q1,q2,q3/3 > q4, for the matches having a total score less than 130
df_under = df[df.iloc[:,3:9].sum(axis=1) < 150]   #selecting total of q1+q2+q3 <130
df_female = df_under[df_under['gender'] == 'F']     #selecting women's mathches
hypo3 = (df_female.iloc[:,3:9].sum(axis=1)/3)+3 > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l3 = hypo3.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l3, "; Total women's matches: ", len(hypo3), ", in percent: ", l3/len(hypo3))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  51 ; Total women's matches:  68 , in percent:  0.75

In [208]:
### women's matches: (q1,q2,q3/3) > q4, for the matches having total score difference between two teams between 10 and 50 at the end of quarter3
df_between = df[((df.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(8,50)]
df_female = df_between[df_between['gender'] == 'F']     #selecting women's mathches
hypo4 = (df_female.iloc[:,3:9].sum(axis=1)/3)+3 > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l4 = hypo4.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l4, "; Total women's matches: ", len(hypo4), ", in percent: ", l4/len(hypo4))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  31 ; Total women's matches:  41 , in percent:  0.7560975609756098

In [209]:
### women's matches: (q1,q2,q3/3) > q4, for the matches having a total score less than 130, and total score difference between two teams between 9 and 50 at the end of quarter 3.
df_between = df[((df.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(8,50)]
df_under = df_between[df_between.iloc[:,3:9].sum(axis=1) < 150]   #selecting total of q1+q2+q3 <150
df_female = df_under[df_under['gender'] == 'F']     #selecting women's mathches
hypo5 = (df_female.iloc[:,3:9].sum(axis=1)/3)+3 > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l5 = hypo5.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l5, "; Total women's matches: ", len(hypo5), ", in percent: ", l5/len(hypo5))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  31 ; Total women's matches:  41 , in percent:  0.7560975609756098

In [212]:
### women's matches: (q1,q2,q3/3) > q4, for the matches having total score difference between two teams between 10 and 50 at the end of quarter3, and avg(q3) > (avg(q2) and avg(q1))
q3_avg = df[['team1q3', 'team2q3']].mean(axis=1)
q2_avg = df[['team1q2', 'team2q2']].mean(axis=1)
q1_avg = df[['team1q1', 'team2q1']].mean(axis=1)
df_cond = df.loc[(q3_avg > q2_avg) & (q3_avg > q1_avg)]

df_between = df_cond[((df_cond.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df_cond.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(7,50)]
df_female = df_between[df_between['gender'] == 'F']     #selecting women's mathches
hypo4 = (df_female.iloc[:,3:9].sum(axis=1)/3) > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l4 = hypo4.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l4, "; Total women's matches: ", len(hypo4), ", in percent: ", l4/len(hypo4))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  8 ; Total women's matches:  15 , in percent:  0.5333333333333333

In [216]:
### women's matches: quarter1<x
totScQ1 = 30    #set threshold score for quarter1
df_female = df[df['gender'] == 'F']     #selecting women's mathches
hypo6 = ((df_female.loc[:,['team1q1', 'team2q1']].sum(axis=1)) < totScQ1).sum()   # number of matches w/ total score in quarter1 less than 46
print("2nd hypothesis: ", hypo6, "; Total women's matches: ", len(df_female), ", in percent: ", hypo6/len(df_female))   # comparison of true hypo of tot sc q1 less than 46 w/ total number of women's matches

2nd hypothesis:  16 ; Total women's matches:  68 , in percent:  0.23529411764705882

In [233]:
### men's matches: quarter1>x
totScQ1 = 46    #set threshold score for quarter1
df_female = df[df['gender'] == 'M']     #selecting men's mathches
hypo6 = ((df_female.loc[:,['team1q1', 'team2q1']].sum(axis=1)) < totScQ1).sum()   # number of matches w/ total score in quarter1 less than totScQ1
print("2nd hypothesis: ", hypo6, "; Total women's matches: ", len(df_female), ", in percent: ", hypo6/len(df_female))   # comparison of true hypo of tot sc q1 less than totScQ1 w/ total number of women's matches

2nd hypothesis:  96 ; Total women's matches:  121 , in percent:  0.7933884297520661

Now we go for greater than (total is greater than)

In [ ]:
### all the matches: (q1+q2+q3)/3 < q4
hypo7 = (df.iloc[:,3:9].sum(axis=1)/3) < df.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l1 = hypo7.sum()    # sum of true hypothesis
print("1st hypothesis: ", l1, ", Total matches: ", len(hypo7), ", in percent: ", l1/len(hypo7))   # comparison of true hypothesis w/ total matches

1st hypothesis:  81 , Total matches:  159 , in percent:  0.5094339622641509

In [245]:
### Men's matches: (q1+q2+q3)/3 < q4
df_male = df[df['gender'] == 'M']     #selecting men's mathches
hypo8 = (df_male.iloc[:,3:9].sum(axis=1)/3) > df_male.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l8 = hypo8.sum()    # sum of true hypothesis
print("1st hypothesis: ", l8, ", Total matches: ", len(hypo8), ", in percent: ", l8/len(hypo8))   # comparison of true hypothesis w/ total matches

1st hypothesis:  48 , Total matches:  121 , in percent:  0.39669421487603307

In [246]:
### Men's matches: (q1+q2+q3)/3 < q4, for the matches having total score difference between two teams between 0 and 10 at the end of quarter3
df_male = df[df['gender'] == 'M']     #selecting men's mathches
df_between = df_male[((df_male.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df_male.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(0,9)]
hypo9 = (df_between.iloc[:,3:9].sum(axis=1)/3) > df_between.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l9 = hypo9.sum()    # sum of true hypothesis
print("1st hypothesis: ", l9, ", Total matches: ", len(hypo9), ", in percent: ", l9/len(hypo9))   # comparison of true hypothesis w/ total matches

1st hypothesis:  33 , Total matches:  72 , in percent:  0.4583333333333333

In [247]:
### Men's matches: (q1+q2+q3)/3 < q4, for the matches having a total score greater than 140
df_male = df[df['gender'] == 'M']     #selecting men's mathches
df_greater = df_male[df_male.iloc[:,3:9].sum(axis=1) > 120]   #selecting total of q1+q2+q3 > 140
hypo9 = (df_greater.iloc[:,3:9].sum(axis=1)/3) > df_greater.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l9 = hypo9.sum()    # sum of true hypothesis
print("1st hypothesis: ", l9, ", Total matches: ", len(hypo9), ", in percent: ", l9/len(hypo9))   # comparison of true hypothesis w/ total matches

1st hypothesis:  25 , Total matches:  55 , in percent:  0.45454545454545453

In [248]:
### Men's matches: (q1+q2+q3)/3 < q4, for the matches having a total score greater than 140, and total score difference between two teams between 0 and 10 at the end of quarter3
df_male = df[df['gender'] == 'M']     #selecting men's mathches
df_greater = df_male[df_male.iloc[:,3:9].sum(axis=1) > 140]   #selecting total of q1+q2+q3 > 140
df_between = df_greater[((df_greater.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df_greater.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(0,7)]
hypo9 = (df_between.iloc[:,3:9].sum(axis=1)/3) < df_between.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l9 = hypo9.sum()    # sum of true hypothesis
print("1st hypothesis: ", l9, ", Total matches: ", len(hypo9), ", in percent: ", l9/len(hypo9))   # comparison of true hypothesis w/ total matches

1st hypothesis:  5 , Total matches:  9 , in percent:  0.5555555555555556

In [249]:
### matches having an average score in first 3 quarters less than the 4th quarter, under this condition: Absolute total score difference between 2 teams between 0 and 5
df_male = df[df['gender'] == 'M']     #selecting men's mathches
df_between = df[((df.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(0,9)]
hypo9 = (df_between.iloc[:,3:9].sum(axis=1)/3) < df_between.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l9 = hypo9.sum()    # sum of true hypothesis
print("1st hypothesis: ", l9, ", Total matches: ", len(hypo9), ", in percent: ", l9/len(hypo9))   # comparison of true hypothesis w/ total matches

1st hypothesis:  52 , Total matches:  102 , in percent:  0.5098039215686274

In [250]:
### Women's matches: (q1,q2,q3/3) > q4, and avg(q3) > (avg(q2) and avg(q1))
q3_avg = df[['team1q3', 'team2q3']].mean(axis=1)
q2_avg = df[['team1q2', 'team2q2']].mean(axis=1)
q1_avg = df[['team1q1', 'team2q1']].mean(axis=1)
df_cond = df.loc[(q3_avg > q2_avg) & (q3_avg > q1_avg)]

df_female = df_cond[df_cond['gender'] == 'F']     #selecting women's mathches
hypo4 = (df_female.iloc[:,3:9].sum(axis=1)/3) > df_female.iloc[:,9:11].sum(axis=1)-4   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l4 = hypo4.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l4, "; Total women's matches: ", len(hypo4), ", in percent: ", l4/len(hypo4))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  18 ; Total women's matches:  23 , in percent:  0.782608695652174