In [1]:
import pandas as pd

# The raw URL for your specific CSV file
url = 'https://raw.githubusercontent.com/mhmdparichehreh/basketball-scores/main/data/scores.csv'

# Read the CSV
df = pd.read_csv(url)

# Display the first 5 rows
df.head()

,ID,date,gender,team1q1,team2q1,team1q2,team2q2,team1q3,team2q3,team1q4,team2q4,team1tot,team2tot,type
0,1,09/12/2025,M,15,11,12,19,28,20,28,12,83,62,NaN
1,2,09/12/2025,F,20,12,13,17,16,19,10,10,59,58,NaN
2,3,10/12/2025,M,28,22,18,21,14,12,22,27,82,82,NaN
3,4,10/12/2025,F,19,10,18,17,24,26,18,18,79,71,NaN
4,5,10/12/2025,M,10,25,13,22,15,20,17,30,55,97,NaN

In [2]:
df

,ID,date,gender,team1q1,team2q1,team1q2,team2q2,team1q3,team2q3,team1q4,team2q4,team1tot,team2tot,type
0,1,09/12/2025,M,15,11,12,19,28,20,28,12,83,62,NaN
1,2,09/12/2025,F,20,12,13,17,16,19,10,10,59,58,NaN
2,3,10/12/2025,M,28,22,18,21,14,12,22,27,82,82,NaN
3,4,10/12/2025,F,19,10,18,17,24,26,18,18,79,71,NaN
4,5,10/12/2025,M,10,25,13,22,15,20,17,30,55,97,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,186,15/02/2026,F,15,19,14,10,17,13,18,17,64,59,europe
185,187,15/02/2026,M,24,15,30,24,25,24,23,22,102,85,georgia
186,188,15/02/2026,F,29,26,13,27,17,20,15,21,74,94,finland
187,189,15/02/2026,F,15,5,12,10,15,15,9,18,51,48,aj
188,190,15/02/2026,F,17,16,15,20,19,16,23,14,74,66,purtugal

In [3]:
### all the matches: (q1+q2+q3)/3 > q4
hypo1 = (df.iloc[:,3:9].sum(axis=1)/3) > df.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l1 = hypo1.sum()    # sum of true hypothesis
print("1st hypothesis: ", l1, "; Total matches: ", len(hypo1), ", in percent: ", l1/len(hypo1))   # comparison of true hypothesis w/ total matches

1st hypothesis:  89 ; Total matches:  189 , in percent:  0.4708994708994709

In [4]:
### all the matches: (q1+q2+q3)/3 < q4
hypo1 = (df.iloc[:,3:9].sum(axis=1)/3) < df.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l1 = hypo1.sum()    # sum of true hypothesis
print("1st hypothesis: ", l1, "; Total matches: ", len(hypo1), ", in percent: ", l1/len(hypo1))   # comparison of true hypothesis w/ total matches

1st hypothesis:  98 ; Total matches:  189 , in percent:  0.5185185185185185

In [5]:
### women's matches: (q1+q2+q3)/3 > q4
df_female = df[df['gender'] == 'F']     #selecting women's mathches
hypo2 = (df_female.iloc[:,3:9].sum(axis=1)/3)+3 > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l2 = hypo2.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l2, "; Total women's matches: ", len(hypo2), ", in percent: ", l2/len(hypo2))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  51 ; Total women's matches:  68 , in percent:  0.75

In [6]:
### women's matches: q1,q2,q3/3 > q4, for the matches having a total score less than 130
df_under = df[df.iloc[:,3:9].sum(axis=1) < 150]   #selecting total of q1+q2+q3 <130
df_female = df_under[df_under['gender'] == 'F']     #selecting women's mathches
hypo3 = (df_female.iloc[:,3:9].sum(axis=1)/3)+3 > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l3 = hypo3.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l3, "; Total women's matches: ", len(hypo3), ", in percent: ", l3/len(hypo3))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  51 ; Total women's matches:  68 , in percent:  0.75

In [7]:
### women's matches: (q1,q2,q3/3) > q4, for the matches having total score difference between two teams between 10 and 50 at the end of quarter3
df_between = df[((df.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(8,50)]
df_female = df_between[df_between['gender'] == 'F']     #selecting women's mathches
hypo4 = (df_female.iloc[:,3:9].sum(axis=1)/3)+3 > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l4 = hypo4.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l4, "; Total women's matches: ", len(hypo4), ", in percent: ", l4/len(hypo4))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  31 ; Total women's matches:  41 , in percent:  0.7560975609756098

In [8]:
### women's matches: (q1,q2,q3/3) > q4, for the matches having a total score less than 130, and total score difference between two teams between 9 and 50 at the end of quarter 3.
df_between = df[((df.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(8,50)]
df_under = df_between[df_between.iloc[:,3:9].sum(axis=1) < 150]   #selecting total of q1+q2+q3 <150
df_female = df_under[df_under['gender'] == 'F']     #selecting women's mathches
hypo5 = (df_female.iloc[:,3:9].sum(axis=1)/3)+3 > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l5 = hypo5.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l5, "; Total women's matches: ", len(hypo5), ", in percent: ", l5/len(hypo5))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  31 ; Total women's matches:  41 , in percent:  0.7560975609756098

In [9]:
### women's matches: (q1,q2,q3/3) > q4, for the matches having total score difference between two teams between 10 and 50 at the end of quarter3, and avg(q3) > (avg(q2) and avg(q1))
q3_avg = df[['team1q3', 'team2q3']].mean(axis=1)
q2_avg = df[['team1q2', 'team2q2']].mean(axis=1)
q1_avg = df[['team1q1', 'team2q1']].mean(axis=1)
df_cond = df.loc[(q3_avg > q2_avg) & (q3_avg > q1_avg)]

df_between = df_cond[((df_cond.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df_cond.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(7,50)]
df_female = df_between[df_between['gender'] == 'F']     #selecting women's mathches
hypo4 = (df_female.iloc[:,3:9].sum(axis=1)/3) > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l4 = hypo4.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l4, "; Total women's matches: ", len(hypo4), ", in percent: ", l4/len(hypo4))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  8 ; Total women's matches:  15 , in percent:  0.5333333333333333

In [10]:
### women's matches: quarter1<x
totScQ1 = 30    #set threshold score for quarter1
df_female = df[df['gender'] == 'F']     #selecting women's mathches
hypo6 = ((df_female.loc[:,['team1q1', 'team2q1']].sum(axis=1)) < totScQ1).sum()   # number of matches w/ total score in quarter1 less than 46
print("2nd hypothesis: ", hypo6, "; Total women's matches: ", len(df_female), ", in percent: ", hypo6/len(df_female))   # comparison of true hypo of tot sc q1 less than 46 w/ total number of women's matches

2nd hypothesis:  16 ; Total women's matches:  68 , in percent:  0.23529411764705882

In [11]:
### men's matches: quarter1>x
totScQ1 = 46    #set threshold score for quarter1
df_female = df[df['gender'] == 'M']     #selecting men's mathches
hypo6 = ((df_female.loc[:,['team1q1', 'team2q1']].sum(axis=1)) < totScQ1).sum()   # number of matches w/ total score in quarter1 less than totScQ1
print("2nd hypothesis: ", hypo6, "; Total women's matches: ", len(df_female), ", in percent: ", hypo6/len(df_female))   # comparison of true hypo of tot sc q1 less than totScQ1 w/ total number of women's matches

2nd hypothesis:  96 ; Total women's matches:  121 , in percent:  0.7933884297520661

Now we go for greater than (total is greater than)

In [12]:
### all the matches: (q1+q2+q3)/3 < q4
hypo7 = (df.iloc[:,3:9].sum(axis=1)/3) < df.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l1 = hypo7.sum()    # sum of true hypothesis
print("1st hypothesis: ", l1, ", Total matches: ", len(hypo7), ", in percent: ", l1/len(hypo7))   # comparison of true hypothesis w/ total matches

1st hypothesis:  98 , Total matches:  189 , in percent:  0.5185185185185185

In [13]:
### Men's matches: (q1+q2+q3)/3 < q4
df_male = df[df['gender'] == 'M']     #selecting men's mathches
hypo8 = (df_male.iloc[:,3:9].sum(axis=1)/3) > df_male.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l8 = hypo8.sum()    # sum of true hypothesis
print("1st hypothesis: ", l8, ", Total matches: ", len(hypo8), ", in percent: ", l8/len(hypo8))   # comparison of true hypothesis w/ total matches

1st hypothesis:  48 , Total matches:  121 , in percent:  0.39669421487603307

In [14]:
### Men's matches: (q1+q2+q3)/3 < q4, for the matches having total score difference between two teams between 0 and 10 at the end of quarter3
df_male = df[df['gender'] == 'M']     #selecting men's mathches
df_between = df_male[((df_male.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df_male.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(0,9)]
hypo9 = (df_between.iloc[:,3:9].sum(axis=1)/3) > df_between.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l9 = hypo9.sum()    # sum of true hypothesis
print("1st hypothesis: ", l9, ", Total matches: ", len(hypo9), ", in percent: ", l9/len(hypo9))   # comparison of true hypothesis w/ total matches

1st hypothesis:  33 , Total matches:  72 , in percent:  0.4583333333333333

In [15]:
### Men's matches: (q1+q2+q3)/3 < q4, for the matches having a total score greater than 140
df_male = df[df['gender'] == 'M']     #selecting men's mathches
df_greater = df_male[df_male.iloc[:,3:9].sum(axis=1) > 120]   #selecting total of q1+q2+q3 > 140
hypo9 = (df_greater.iloc[:,3:9].sum(axis=1)/3) > df_greater.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l9 = hypo9.sum()    # sum of true hypothesis
print("1st hypothesis: ", l9, ", Total matches: ", len(hypo9), ", in percent: ", l9/len(hypo9))   # comparison of true hypothesis w/ total matches

1st hypothesis:  25 , Total matches:  55 , in percent:  0.45454545454545453

In [16]:
### Men's matches: (q1+q2+q3)/3 < q4, for the matches having a total score greater than 140, and total score difference between two teams between 0 and 10 at the end of quarter3
df_male = df[df['gender'] == 'M']     #selecting men's mathches
df_greater = df_male[df_male.iloc[:,3:9].sum(axis=1) > 140]   #selecting total of q1+q2+q3 > 140
df_between = df_greater[((df_greater.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df_greater.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(0,7)]
hypo9 = (df_between.iloc[:,3:9].sum(axis=1)/3) < df_between.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l9 = hypo9.sum()    # sum of true hypothesis
print("1st hypothesis: ", l9, ", Total matches: ", len(hypo9), ", in percent: ", l9/len(hypo9))   # comparison of true hypothesis w/ total matches

1st hypothesis:  5 , Total matches:  9 , in percent:  0.5555555555555556

In [17]:
### matches having an average score in first 3 quarters less than the 4th quarter, under this condition: Absolute total score difference between 2 teams between 0 and 5
df_male = df[df['gender'] == 'M']     #selecting men's mathches
df_between = df[((df.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(0,9)]
hypo9 = (df_between.iloc[:,3:9].sum(axis=1)/3) < df_between.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l9 = hypo9.sum()    # sum of true hypothesis
print("1st hypothesis: ", l9, ", Total matches: ", len(hypo9), ", in percent: ", l9/len(hypo9))   # comparison of true hypothesis w/ total matches

1st hypothesis:  52 , Total matches:  102 , in percent:  0.5098039215686274

In [18]:
### Women's matches: (q1,q2,q3/3) > q4, and avg(q3) > (avg(q2) and avg(q1))
q3_avg = df[['team1q3', 'team2q3']].mean(axis=1)
q2_avg = df[['team1q2', 'team2q2']].mean(axis=1)
q1_avg = df[['team1q1', 'team2q1']].mean(axis=1)
df_cond = df.loc[(q3_avg > q2_avg) & (q3_avg > q1_avg)]

df_female = df_cond[df_cond['gender'] == 'F']     #selecting women's mathches
hypo4 = (df_female.iloc[:,3:9].sum(axis=1)/3) > df_female.iloc[:,9:11].sum(axis=1)-4   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l4 = hypo4.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l4, "; Total women's matches: ", len(hypo4), ", in percent: ", l4/len(hypo4))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  18 ; Total women's matches:  23 , in percent:  0.782608695652174

Data Augmentation:

In [19]:
import pandas as pd

# 2. Define the exact column swaps
swap_mapping = {
    "team1q1": "team2q1", "team2q1": "team1q1",
    "team1q2": "team2q2", "team2q2": "team1q2",
    "team1q3": "team2q3", "team2q3": "team1q3",
    "team1q4": "team2q4", "team2q4": "team1q4",
    "team1tot": "team2tot", "team2tot": "team1tot"
}

# 3. Create the swapped copy
# Renaming the columns means "team1q1" data is now labeled "team2q1"
df_swapped = df.rename(columns=swap_mapping)

# 4. Append the swapped data to the original dataset
df_augmented = pd.concat([df, df_swapped], ignore_index=True)

print("Original Data Size:", len(df))
print("Augmented Data Size:", len(df_augmented))
print("\nAugmented DataFrame:")
df_augmented

Original Data Size: 189
Augmented Data Size: 378

Augmented DataFrame:

,ID,date,gender,team1q1,team2q1,team1q2,team2q2,team1q3,team2q3,team1q4,team2q4,team1tot,team2tot,type
0,1,09/12/2025,M,15,11,12,19,28,20,28,12,83,62,NaN
1,2,09/12/2025,F,20,12,13,17,16,19,10,10,59,58,NaN
2,3,10/12/2025,M,28,22,18,21,14,12,22,27,82,82,NaN
3,4,10/12/2025,F,19,10,18,17,24,26,18,18,79,71,NaN
4,5,10/12/2025,M,10,25,13,22,15,20,17,30,55,97,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,186,15/02/2026,F,19,15,10,14,13,17,17,18,59,64,europe
374,187,15/02/2026,M,15,24,24,30,24,25,22,23,85,102,georgia
375,188,15/02/2026,F,26,29,27,13,20,17,21,15,94,74,finland
376,189,15/02/2026,F,5,15,10,12,15,15,18,9,48,51,aj
377,190,15/02/2026,F,16,17,20,15,16,19,14,23,66,74,purtugal

K-Means implementation:

In [20]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

# 2. Preprocessing
# Convert categorical 'gender' to numerical so KNN can calculate distance
df_augmented['gender_num'] = df_augmented['gender'].map({'M': 0, 'F': 1})

# Define our feature matrix
features = ["gender_num", "team1q1", "team2q1", "team1q2", "team2q2", "team1q3", "team2q3"]
X = df_augmented[features]

# Scale the features (Crucial for KNN!)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 3. Fit the KNN Model
# n_neighbors=5 as requested. 'euclidean' is the standard straight-line distance.
knn = NearestNeighbors(n_neighbors=5, metric='euclidean')
knn.fit(X_scaled)

# 4. Create the search function
def find_similar_matches(input_gender, t1q1, t2q1, t1q2, t2q2, t1q3, t2q3):
    """Finds the 5 matches closest to the provided input."""

    # Encode input gender to match our training data
    gen_num = 1 if input_gender.upper() == 'F' else 0

    # Format as a 2D array and scale it using the SAME scaler
    input_data = pd.DataFrame(
        [[gen_num, t1q1, t2q1, t1q2, t2q2, t1q3, t2q3]],
        columns=features
    )
    input_scaled = scaler.transform(input_data)

    # Calculate distances and get the indices of the closest matches
    distances, indices = knn.kneighbors(input_scaled)

    # Fetch the actual rows from the original dataframe
    # We use indices[0] because kneighbors returns an array of arrays
    closest_matches = df_augmented.iloc[indices[0]].copy()

    # Optional: Add the distance score so you can see how close they are
    closest_matches['match_distance'] = distances[0]

    # Drop the temporary numerical gender column for cleaner output
    return closest_matches

# --- Example Usage ---
# Let's search for a Men's game with roughly these quarter scores:
results = find_similar_matches('M', 24, 21, 23, 25, 27, 24)

print("Top 5 Closest Matches:\n")
print(results)

Top 5 Closest Matches:

      ID        date gender  team1q1  team2q1  team1q2  team2q2  team1q3  \
251   63  25/01/2026      M       22       23       24       25       27
78    79  25/01/2026      M       22       26       24       28       23
267   79  25/01/2026      M       26       22       28       24       21
62    63  25/01/2026      M       23       22       25       24       20
343  156  15/02/2026      M       21       17       19       22       25

     team2q3  team1q4  team2q4  team1tot  team2tot       type  gender_num  \
251       20       35       46       108       114        NaN           0
78        21       39       32       108       107        NaN           0
267       23       32       39       107       108        NaN           0
62        27       46       35       114       108        NaN           0
343       20       14       12        79        71  argentina           0

     match_distance
251        0.912547
78         1.442490
267        1.469812
62         1.475114
343        1.486030

In [38]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

# 2. Feature Engineering: Calculate the combined quarter sums
df['q1_sum'] = df['team1q1'] + df['team2q1']
df['q2_sum'] = df['team1q2'] + df['team2q2']
df['q3_sum'] = df['team1q3'] + df['team2q3']
df['q4_sum'] = df['team1q4'] + df['team2q4']
df['tot_dif'] = (df['team1q1'] + df['team1q2'] + df['team1q3'] - df['team2q1'] - df['team2q2'] - df['team2q3']).abs() #difference between two teams until 3rd quarter

# Convert gender to numerical
df['gender_num'] = df['gender'].map({'M': 0, 'F': 1})

# 3. Define our new feature matrix
features = ["gender_num", "q1_sum", "q2_sum", "q3_sum", "tot_dif"]
X = df[features]

# 4. Scale and Fit the KNN Model
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

knn = NearestNeighbors(n_neighbors=10, metric='euclidean')
knn.fit(X_scaled)

# 5. Create the search function for summed scores
def find_similar_by_quarter_totals(input_gender, q1_total, q2_total, q3_total, dif):
    """Finds the 5 matches with the most similar combined quarter scores."""

    # Encode input gender
    gen_num = 1 if input_gender.upper() == 'F' else 0

    # Format and scale input
    input_data = pd.DataFrame(
        [[gen_num, q1_total, q2_total, q3_total, dif]],
        columns=features
    )
    input_scaled = scaler.transform(input_data)

    # Get neighbors
    distances, indices = knn.kneighbors(input_scaled)

    # Fetch the original rows
    closest_matches = df.iloc[indices[0]].copy()
    closest_matches['match_distance'] = distances[0]

    # Return just the relevant columns for a cleaner view
    return closest_matches

# --- Example Usage ---
# Searching for a Men's game where the combined quarter totals were 45, 46, and 50
results = find_similar_by_quarter_totals('M', 45, 46, 50, 5)

print("Top 5 Matches by Combined Quarter Scores:\n")
print(results)

Top 5 Matches by Combined Quarter Scores:

      ID        date gender  team1q1  team2q1  team1q2  team2q2  team1q3  \
62    63  25/01/2026      M       23       22       25       24       20
106  107  25/01/2026      M       22       25       31       18       20
132  134  26/01/2026      M       20       24       17       24       25
83    84  25/01/2026      M       21       22       19       24       30
103  104  25/01/2026      M       23       29       26       22       27
42    43  25/01/2026      M       26       18       30       14       18
153  155  15/02/2026      M       20       20       16       25       23
52    53  25/01/2026      M       20       19       14       26       28
107  108  25/01/2026      M       23       21       16       21       28
78    79  25/01/2026      M       22       26       24       28       23

     team2q3  team1q4  ...  team1tot  team2tot       type q1_sum  q2_sum  \
62        27       46  ...       114       108        NaN     45      49
106       26       15  ...        88        91        NaN     47      49
132       21       30  ...        92        88        NaN     44      41
83        15       20  ...        90        86        NaN     43      43
103       20       36  ...       112       108        NaN     52      48
42        28       19  ...        93        87        NaN     44      44
153       25       20  ...        79        91  argentina     40      41
52        24       18  ...        80        90        NaN     39      40
107       19       19  ...        86        79        NaN     44      37
78        21       39  ...       108       107        NaN     48      52

     q3_sum  q4_sum  gender_num  tot_dif  match_distance
62       47      81           0        5        0.542798
106      46      37           0        4        0.707495
132      46      49           0        7        0.835392
83       45      45           0        9        0.892049
103      47      73           0        5        1.012155
42       46      46           0       14        1.024338
153      48      41           0       11        1.062549
52       52      39           0        7        1.092595
107      47      37           0        6        1.146673
78       44      71           0        6        1.154818

[10 rows x 21 columns]

In [41]:
results = find_similar_by_quarter_totals('F', 51, 41, 45, 3)

print("Top 5 Matches by Combined Quarter Scores:\n")
print(results)

Top 5 Matches by Combined Quarter Scores:

      ID        date gender  team1q1  team2q1  team1q2  team2q2  team1q3  \
186  188  15/02/2026      F       29       26       13       27       17
87    88  25/01/2026      F       13       26       29       15       22
91    92  25/01/2026      F       23       24       11       25       18
166  168  15/02/2026      F       25       24       23       16       11
96    97  25/01/2026      F       22       31       27       17       15
8      9  10/12/2025      F       17       23       18       21       19
156  158  15/02/2026      F       14       28       27       15       17
44    45  25/01/2026      M       19       33       31       11       22
119  120  25/01/2026      F       19       27       14       12       20
64    65  25/01/2026      F       21       17       22       18       21

     team2q3  team1q4  ...  team1tot  team2tot     type q1_sum  q2_sum  \
186       20       15  ...        74        94  finland     55      40
87        19       18  ...        82        80      NaN     39      44
91        21        9  ...        61        83      NaN     47      36
166       21       27  ...        86        80   turkey     49      39
96        17       26  ...        90        85      NaN     53      44
8         26       20  ...        74        94      NaN     40      39
156       16       13  ...        71        72   mexico     42      42
44        23       17  ...        89        95      NaN     52      42
119       18       20  ...        73        67      NaN     46      26
64        16       13  ...        77        70      NaN     38      40

     q3_sum  q4_sum  gender_num  tot_dif  match_distance
186      37      36           1       14        1.579047
87       41      38           1        4        1.668325
91       39      22           1       18        1.778371
166      32      46           1        2        1.823320
96       32      46           1        1        1.848956
8        45      44           1       16        1.853868
156      33      26           1        1        2.022575
44       45      45           0        5        2.098777
119      38      30           1        4        2.110386
64       37      32           1       13        2.193875

[10 rows x 21 columns]