In [1]:
import pandas as pd

# The raw URL for your specific CSV file
url = 'https://raw.githubusercontent.com/mhmdparichehreh/basketball-scores/main/data/scores.csv'

# Read the CSV
df = pd.read_csv(url)

# Display the first 5 rows
df.head()

,ID,date,gender,team1q1,team2q1,team1q2,team2q2,team1q3,team2q3,team1q4,team2q4,team1tot,team2tot,type
0,1,09/12/2025,M,15,11,12,19,28,20,28,12,83,62,NaN
1,2,09/12/2025,F,20,12,13,17,16,19,10,10,59,58,NaN
2,3,10/12/2025,M,28,22,18,21,14,12,22,27,82,82,NaN
3,4,10/12/2025,F,19,10,18,17,24,26,18,18,79,71,NaN
4,5,10/12/2025,M,10,25,13,22,15,20,17,30,55,97,NaN

In [2]:
df

,ID,date,gender,team1q1,team2q1,team1q2,team2q2,team1q3,team2q3,team1q4,team2q4,team1tot,team2tot,type
0,1,09/12/2025,M,15,11,12,19,28,20,28,12,83,62,NaN
1,2,09/12/2025,F,20,12,13,17,16,19,10,10,59,58,NaN
2,3,10/12/2025,M,28,22,18,21,14,12,22,27,82,82,NaN
3,4,10/12/2025,F,19,10,18,17,24,26,18,18,79,71,NaN
4,5,10/12/2025,M,10,25,13,22,15,20,17,30,55,97,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,237,11/04/2026,F,22,20,18,6,6,17,19,10,65,53,NaN
235,238,11/04/2026,M,22,27,13,20,20,16,13,15,68,78,NaN
236,239,11/04/2026,M,21,21,18,9,17,12,22,16,78,58,NaN
237,240,11/04/2026,M,15,12,27,7,22,12,15,12,79,43,NaN
238,241,11/04/2026,M,27,21,23,17,23,26,26,22,99,86,NaN

In [3]:
### all the matches: (q1+q2+q3)/3 > q4
hypo1 = (df.iloc[:,3:9].sum(axis=1)/3) > df.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l1 = hypo1.sum()    # sum of true hypothesis
print("1st hypothesis: ", l1, "; Total matches: ", len(hypo1), ", in percent: ", l1/len(hypo1))   # comparison of true hypothesis w/ total matches

1st hypothesis:  114 ; Total matches:  239 , in percent:  0.4769874476987448

In [4]:
### all the matches: (q1+q2+q3)/3 < q4
hypo1 = (df.iloc[:,3:9].sum(axis=1)/3) < df.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l1 = hypo1.sum()    # sum of true hypothesis
print("1st hypothesis: ", l1, "; Total matches: ", len(hypo1), ", in percent: ", l1/len(hypo1))   # comparison of true hypothesis w/ total matches

1st hypothesis:  122 ; Total matches:  239 , in percent:  0.5104602510460251

In [5]:
### women's matches: (q1+q2+q3)/3 > q4
df_female = df[df['gender'] == 'F']     #selecting women's mathches
hypo2 = (df_female.iloc[:,3:9].sum(axis=1)/3)+3 > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l2 = hypo2.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l2, "; Total women's matches: ", len(hypo2), ", in percent: ", l2/len(hypo2))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  61 ; Total women's matches:  78 , in percent:  0.782051282051282

In [6]:
### women's matches: q1,q2,q3/3 > q4, for the matches having a total score less than 130
df_under = df[df.iloc[:,3:9].sum(axis=1) < 150]   #selecting total of q1+q2+q3 <130
df_female = df_under[df_under['gender'] == 'F']     #selecting women's mathches
hypo3 = (df_female.iloc[:,3:9].sum(axis=1)/3)+3 > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l3 = hypo3.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l3, "; Total women's matches: ", len(hypo3), ", in percent: ", l3/len(hypo3))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  61 ; Total women's matches:  78 , in percent:  0.782051282051282

In [7]:
### women's matches: (q1,q2,q3/3) > q4, for the matches having total score difference between two teams between 10 and 50 at the end of quarter3
df_between = df[((df.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(8,50)]
df_female = df_between[df_between['gender'] == 'F']     #selecting women's mathches
hypo4 = (df_female.iloc[:,3:9].sum(axis=1)/3)+3 > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l4 = hypo4.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l4, "; Total women's matches: ", len(hypo4), ", in percent: ", l4/len(hypo4))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  37 ; Total women's matches:  47 , in percent:  0.7872340425531915

In [8]:
### women's matches: (q1,q2,q3/3) > q4, for the matches having a total score less than 130, and total score difference between two teams between 9 and 50 at the end of quarter 3.
df_between = df[((df.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(8,50)]
df_under = df_between[df_between.iloc[:,3:9].sum(axis=1) < 150]   #selecting total of q1+q2+q3 <150
df_female = df_under[df_under['gender'] == 'F']     #selecting women's mathches
hypo5 = (df_female.iloc[:,3:9].sum(axis=1)/3)+3 > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l5 = hypo5.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l5, "; Total women's matches: ", len(hypo5), ", in percent: ", l5/len(hypo5))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  37 ; Total women's matches:  47 , in percent:  0.7872340425531915

In [9]:
### women's matches: (q1,q2,q3/3) > q4, for the matches having total score difference between two teams between 10 and 50 at the end of quarter3, and avg(q3) > (avg(q2) and avg(q1))
q3_avg = df[['team1q3', 'team2q3']].mean(axis=1)
q2_avg = df[['team1q2', 'team2q2']].mean(axis=1)
q1_avg = df[['team1q1', 'team2q1']].mean(axis=1)
df_cond = df.loc[(q3_avg > q2_avg) & (q3_avg > q1_avg)]

df_between = df_cond[((df_cond.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df_cond.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(7,50)]
df_female = df_between[df_between['gender'] == 'F']     #selecting women's mathches
hypo4 = (df_female.iloc[:,3:9].sum(axis=1)/3) > df_female.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l4 = hypo4.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l4, "; Total women's matches: ", len(hypo4), ", in percent: ", l4/len(hypo4))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  10 ; Total women's matches:  17 , in percent:  0.5882352941176471

In [10]:
### women's matches: quarter1<x
totScQ1 = 30    #set threshold score for quarter1
df_female = df[df['gender'] == 'F']     #selecting women's mathches
hypo6 = ((df_female.loc[:,['team1q1', 'team2q1']].sum(axis=1)) < totScQ1).sum()   # number of matches w/ total score in quarter1 less than 46
print("2nd hypothesis: ", hypo6, "; Total women's matches: ", len(df_female), ", in percent: ", hypo6/len(df_female))   # comparison of true hypo of tot sc q1 less than 46 w/ total number of women's matches

2nd hypothesis:  17 ; Total women's matches:  78 , in percent:  0.21794871794871795

In [11]:
### men's matches: quarter1>x
totScQ1 = 46    #set threshold score for quarter1
df_female = df[df['gender'] == 'M']     #selecting men's mathches
hypo6 = ((df_female.loc[:,['team1q1', 'team2q1']].sum(axis=1)) < totScQ1).sum()   # number of matches w/ total score in quarter1 less than totScQ1
print("2nd hypothesis: ", hypo6, "; Total women's matches: ", len(df_female), ", in percent: ", hypo6/len(df_female))   # comparison of true hypo of tot sc q1 less than totScQ1 w/ total number of women's matches

2nd hypothesis:  120 ; Total women's matches:  161 , in percent:  0.7453416149068323

Now we go for greater than (total is greater than)

In [12]:
### all the matches: (q1+q2+q3)/3 < q4
hypo7 = (df.iloc[:,3:9].sum(axis=1)/3) < df.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l1 = hypo7.sum()    # sum of true hypothesis
print("1st hypothesis: ", l1, ", Total matches: ", len(hypo7), ", in percent: ", l1/len(hypo7))   # comparison of true hypothesis w/ total matches

1st hypothesis:  122 , Total matches:  239 , in percent:  0.5104602510460251

In [13]:
### Men's matches: (q1+q2+q3)/3 < q4
df_male = df[df['gender'] == 'M']     #selecting men's mathches
hypo8 = (df_male.iloc[:,3:9].sum(axis=1)/3) > df_male.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l8 = hypo8.sum()    # sum of true hypothesis
print("1st hypothesis: ", l8, ", Total matches: ", len(hypo8), ", in percent: ", l8/len(hypo8))   # comparison of true hypothesis w/ total matches

1st hypothesis:  64 , Total matches:  161 , in percent:  0.39751552795031053

In [14]:
### Men's matches: (q1+q2+q3)/3 < q4, for the matches having total score difference between two teams between 0 and 10 at the end of quarter3
df_male = df[df['gender'] == 'M']     #selecting men's mathches
df_between = df_male[((df_male.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df_male.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(0,9)]
hypo9 = (df_between.iloc[:,3:9].sum(axis=1)/3) > df_between.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l9 = hypo9.sum()    # sum of true hypothesis
print("1st hypothesis: ", l9, ", Total matches: ", len(hypo9), ", in percent: ", l9/len(hypo9))   # comparison of true hypothesis w/ total matches

1st hypothesis:  44 , Total matches:  99 , in percent:  0.4444444444444444

In [15]:
### Men's matches: (q1+q2+q3)/3 < q4, for the matches having a total score greater than 140
df_male = df[df['gender'] == 'M']     #selecting men's mathches
df_greater = df_male[df_male.iloc[:,3:9].sum(axis=1) > 120]   #selecting total of q1+q2+q3 > 140
hypo9 = (df_greater.iloc[:,3:9].sum(axis=1)/3) > df_greater.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l9 = hypo9.sum()    # sum of true hypothesis
print("1st hypothesis: ", l9, ", Total matches: ", len(hypo9), ", in percent: ", l9/len(hypo9))   # comparison of true hypothesis w/ total matches

1st hypothesis:  33 , Total matches:  77 , in percent:  0.42857142857142855

In [16]:
### Men's matches: (q1+q2+q3)/3 < q4, for the matches having a total score greater than 140, and total score difference between two teams between 0 and 10 at the end of quarter3
df_male = df[df['gender'] == 'M']     #selecting men's mathches
df_greater = df_male[df_male.iloc[:,3:9].sum(axis=1) > 140]   #selecting total of q1+q2+q3 > 140
df_between = df_greater[((df_greater.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df_greater.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(0,7)]
hypo9 = (df_between.iloc[:,3:9].sum(axis=1)/3) < df_between.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l9 = hypo9.sum()    # sum of true hypothesis
print("1st hypothesis: ", l9, ", Total matches: ", len(hypo9), ", in percent: ", l9/len(hypo9))   # comparison of true hypothesis w/ total matches

1st hypothesis:  9 , Total matches:  15 , in percent:  0.6

In [17]:
### matches having an average score in first 3 quarters less than the 4th quarter, under this condition: Absolute total score difference between 2 teams between 0 and 5
df_male = df[df['gender'] == 'M']     #selecting men's mathches
df_between = df[((df.loc[:,['team1q1', 'team1q2', 'team1q3']].sum(axis=1) - df.loc[:,['team2q1', 'team2q2', 'team2q3']].sum(axis=1)).abs()).between(0,9)]
hypo9 = (df_between.iloc[:,3:9].sum(axis=1)/3) < df_between.iloc[:,9:11].sum(axis=1)   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 < total scores of quarter4
l9 = hypo9.sum()    # sum of true hypothesis
print("1st hypothesis: ", l9, ", Total matches: ", len(hypo9), ", in percent: ", l9/len(hypo9))   # comparison of true hypothesis w/ total matches

1st hypothesis:  68 , Total matches:  134 , in percent:  0.5074626865671642

In [18]:
### Women's matches: (q1,q2,q3/3) > q4, and avg(q3) > (avg(q2) and avg(q1))
q3_avg = df[['team1q3', 'team2q3']].mean(axis=1)
q2_avg = df[['team1q2', 'team2q2']].mean(axis=1)
q1_avg = df[['team1q1', 'team2q1']].mean(axis=1)
df_cond = df.loc[(q3_avg > q2_avg) & (q3_avg > q1_avg)]

df_female = df_cond[df_cond['gender'] == 'F']     #selecting women's mathches
hypo4 = (df_female.iloc[:,3:9].sum(axis=1)/3) > df_female.iloc[:,9:11].sum(axis=1)-4   # hypo1 = (total scores of quarter1, quarter2 and quarter3)/3 > total scores of quarter4
l4 = hypo4.sum()    # sum of true hypothesis
print("2nd hypothesis: ", l4, "; Total women's matches: ", len(hypo4), ", in percent: ", l4/len(hypo4))   # comparison of true hypothesis w/ total women's matches

2nd hypothesis:  20 ; Total women's matches:  25 , in percent:  0.8

Data Augmentation:

In [19]:
import pandas as pd

# 2. Define the exact column swaps
swap_mapping = {
    "team1q1": "team2q1", "team2q1": "team1q1",
    "team1q2": "team2q2", "team2q2": "team1q2",
    "team1q3": "team2q3", "team2q3": "team1q3",
    "team1q4": "team2q4", "team2q4": "team1q4",
    "team1tot": "team2tot", "team2tot": "team1tot"
}

# 3. Create the swapped copy
# Renaming the columns means "team1q1" data is now labeled "team2q1"
df_swapped = df.rename(columns=swap_mapping)

# 4. Append the swapped data to the original dataset
df_augmented = pd.concat([df, df_swapped], ignore_index=True)

print("Original Data Size:", len(df))
print("Augmented Data Size:", len(df_augmented))
print("\nAugmented DataFrame:")
df_augmented

Original Data Size: 239
Augmented Data Size: 478

Augmented DataFrame:

,ID,date,gender,team1q1,team2q1,team1q2,team2q2,team1q3,team2q3,team1q4,team2q4,team1tot,team2tot,type
0,1,09/12/2025,M,15,11,12,19,28,20,28,12,83,62,NaN
1,2,09/12/2025,F,20,12,13,17,16,19,10,10,59,58,NaN
2,3,10/12/2025,M,28,22,18,21,14,12,22,27,82,82,NaN
3,4,10/12/2025,F,19,10,18,17,24,26,18,18,79,71,NaN
4,5,10/12/2025,M,10,25,13,22,15,20,17,30,55,97,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,237,11/04/2026,F,20,22,6,18,17,6,10,19,53,65,NaN
474,238,11/04/2026,M,27,22,20,13,16,20,15,13,78,68,NaN
475,239,11/04/2026,M,21,21,9,18,12,17,16,22,58,78,NaN
476,240,11/04/2026,M,12,15,7,27,12,22,12,15,43,79,NaN
477,241,11/04/2026,M,21,27,17,23,26,23,22,26,86,99,NaN

K-Means implementation:

In [20]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

# 2. Preprocessing
# Convert categorical 'gender' to numerical so KNN can calculate distance
df_augmented['gender_num'] = df_augmented['gender'].map({'M': 0, 'F': 1})

# Define our feature matrix
features = ["gender_num", "team1q1", "team2q1", "team1q2", "team2q2", "team1q3", "team2q3"]
X = df_augmented[features]

# Scale the features (Crucial for KNN!)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 3. Fit the KNN Model
# n_neighbors=5 as requested. 'euclidean' is the standard straight-line distance.
knn = NearestNeighbors(n_neighbors=5, metric='euclidean')
knn.fit(X_scaled)

# 4. Create the search function
def find_similar_matches(input_gender, t1q1, t2q1, t1q2, t2q2, t1q3, t2q3):
    """Finds the 5 matches closest to the provided input."""

    # Encode input gender to match our training data
    gen_num = 1 if input_gender.upper() == 'F' else 0

    # Format as a 2D array and scale it using the SAME scaler
    input_data = pd.DataFrame(
        [[gen_num, t1q1, t2q1, t1q2, t2q2, t1q3, t2q3]],
        columns=features
    )
    input_scaled = scaler.transform(input_data)

    # Calculate distances and get the indices of the closest matches
    distances, indices = knn.kneighbors(input_scaled)

    # Fetch the actual rows from the original dataframe
    # We use indices[0] because kneighbors returns an array of arrays
    closest_matches = df_augmented.iloc[indices[0]].copy()

    # Optional: Add the distance score so you can see how close they are
    closest_matches['match_distance'] = distances[0]

    # Drop the temporary numerical gender column for cleaner output
    return closest_matches

# --- Example Usage ---
# Let's search for a Men's game with roughly these quarter scores:
results = find_similar_matches('M', 24, 21, 23, 25, 27, 24)

print("Top 5 Closest Matches:\n")
print(results)

Top 5 Closest Matches:

      ID        date gender  team1q1  team2q1  team1q2  team2q2  team1q3  \
209  211  09/04/2026      M       24       22       20       24       28
301   63  25/01/2026      M       22       23       24       25       27
448  211  09/04/2026      M       22       24       24       20       26
193  195  09/04/2026      M       25       19       23       28       22
62    63  25/01/2026      M       23       22       25       24       20

     team2q3  team1q4  team2q4  team1tot  team2tot type  gender_num  \
209       26       25       18        97        90  NaN           0
301       20       35       46       108       114  NaN           0
448       28       18       25        90        97  NaN           0
193       29       28       29        98       105  NaN           0
62        27       46       35       114       108  NaN           0

     match_distance
209        0.637907
301        0.832601
448        1.216216
193        1.305598
62         1.315338

In [21]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

# 2. Feature Engineering: Calculate the combined quarter sums
df['q1_sum'] = df['team1q1'] + df['team2q1']
df['q2_sum'] = df['team1q2'] + df['team2q2']
df['q3_sum'] = df['team1q3'] + df['team2q3']
df['q4_sum'] = df['team1q4'] + df['team2q4']
df['tot_dif'] = (df['team1q1'] + df['team1q2'] + df['team1q3'] - df['team2q1'] - df['team2q2'] - df['team2q3']).abs() #difference between two teams until 3rd quarter

# Convert gender to numerical
df['gender_num'] = df['gender'].map({'M': 0, 'F': 1})

# 3. Define our new feature matrix
features = ["gender_num", "q1_sum", "q2_sum", "q3_sum", "tot_dif"]
X = df[features]

# 4. Scale and Fit the KNN Model
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

knn = NearestNeighbors(n_neighbors=10, metric='euclidean')
knn.fit(X_scaled)

# 5. Create the search function for summed scores
def find_similar_by_quarter_totals(input_gender, q1_total, q2_total, q3_total, dif):
    """Finds the 5 matches with the most similar combined quarter scores."""

    # Encode input gender
    gen_num = 1 if input_gender.upper() == 'F' else 0

    # Format and scale input
    input_data = pd.DataFrame(
        [[gen_num, q1_total, q2_total, q3_total, dif]],
        columns=features
    )
    input_scaled = scaler.transform(input_data)

    # Get neighbors
    distances, indices = knn.kneighbors(input_scaled)

    # Fetch the original rows
    closest_matches = df.iloc[indices[0]].copy()
    closest_matches['match_distance'] = distances[0]

    # Return just the relevant columns for a cleaner view
    return closest_matches

# --- Example Usage ---
# Searching for a Men's game where the combined quarter totals were 45, 46, and 50
results = find_similar_by_quarter_totals('M', 45, 46, 50, 5)

print("Top 5 Matches by Combined Quarter Scores:\n")
print(results)

Top 5 Matches by Combined Quarter Scores:

      ID        date gender  team1q1  team2q1  team1q2  team2q2  team1q3  \
62    63  25/01/2026      M       23       22       25       24       20
193  195  09/04/2026      M       25       19       23       28       22
106  107  25/01/2026      M       22       25       31       18       20
209  211  09/04/2026      M       24       22       20       24       28
132  134  26/01/2026      M       20       24       17       24       25
83    84  25/01/2026      M       21       22       19       24       30
238  241  11/04/2026      M       27       21       23       17       23
103  104  25/01/2026      M       23       29       26       22       27
200  202  09/04/2026      M       17       28       23       19       20
42    43  25/01/2026      M       26       18       30       14       18

     team2q3  team1q4  ...  team1tot  team2tot  type q1_sum  q2_sum  q3_sum  \
62        27       46  ...       114       108   NaN     45      49      47
193       29       28  ...        98       105   NaN     44      51      51
106       26       15  ...        88        91   NaN     47      49      46
209       26       25  ...        97        90   NaN     46      44      54
132       21       30  ...        92        88   NaN     44      41      46
83        15       20  ...        90        86   NaN     43      43      45
238       26       26  ...        99        86   NaN     48      40      49
103       20       36  ...       112       108   NaN     52      48      47
200       26       27  ...        87        91   NaN     45      42      46
42        28       19  ...        93        87   NaN     44      44      46

     q4_sum  tot_dif  gender_num  match_distance
62       81        5           0        0.451484
193      57        6           0        0.540309
106      37        4           0        0.594280
209      43        0           0        0.681078
132      49        7           0        0.708895
83       45        9           0        0.768891
238      48        9           0        0.800629
103      73        5           0        0.905083
200      45       13           0        0.950678
42       46       14           0        0.968298

[10 rows x 21 columns]

In [34]:
gen = 'F'
q1, q2, q3 = 32, 28, 26
dif = 12
results = find_similar_by_quarter_totals(gen, q1, q2, q3, dif)

print("Top 5 Matches by Combined Quarter Scores:\n")
print(results)
print("Min: ", results['q4_sum'].min(), ", Max: ", results['q4_sum'].max())
print("(", q1+q2+q3+results['q4_sum'].min(), ",", q1+q2+q3+results['q4_sum'].max(),")")

Top 5 Matches by Combined Quarter Scores:

      ID        date gender  team1q1  team2q1  team1q2  team2q2  team1q3  \
37    38  25/01/2026      F       19       15       18        8       13
43    44  25/01/2026      F       19       15       18        8       13
118  119  25/01/2026      F       15       14       19       10       16
184  186  15/02/2026      F       15       19       14       10       17
146  148  14/02/2026      F       18        8       15       16       17
46    47  25/01/2026      F       19       17       15       17       13
145  147  14/02/2026      F       11       27       15       14       14
163  165  15/02/2026      F       21       12       17       20       16
175  177  15/02/2026      F       14       13        6       17       17
82    83  25/01/2026      F       26        8       15       20       19

     team2q3  team1q4  ...  team1tot  team2tot     type q1_sum  q2_sum  \
37        15       14  ...        64        50      NaN     34      26
43        15       14  ...        64        50      NaN     34      26
118       11       17  ...        67        47      NaN     29      29
184       13       18  ...        64        59   europe     34      24
146       15       21  ...        71        57  america     26      31
46        21       23  ...        70        72      NaN     36      32
145       18       14  ...        54        82  america     38      29
163       16       15  ...        69        64   russia     33      37
175        2       15  ...        52        42    spain     27      23
82        17       26  ...        86        64      NaN     34      35

     q3_sum  q4_sum  tot_dif  gender_num  match_distance
37       28      26       12           1        0.380829
43       28      26       12           1        0.380829
118      27      29       15           1        0.470389
184      30      35        4           1        0.978889
146      32      39       11           1        1.017652
46       34      40        8           1        1.143755
145      32      37       19           1        1.165876
163      32      31        6           1        1.263738
175      19      25        5           1        1.271734
82       36      45       15           1        1.367516

[10 rows x 21 columns]
Min:  25 , Max:  45
( 111 , 131 )